### ISSUE TITLE
Pushing a theme overwrites settings and section data

### ISSUE THREAD

**Issue by marcdstudio** [younessidbakkasse/workflow#24]
When running yarn start or yarn deploy, any dynamic section data or theme settings that have been added since the last start / deploy are erased. I'm imaging this has something to do with [this similar issue](https://community.shopify.com/c/technical-q-a/shopify-cli-pushing-a-theme-overwrites-settings-and-section-data/m-p/1293447) and might be able to be resolved with adding an --ignore option for the json templates like [described here](https://github.com/Shopify/shopify-cli/pull/1479). Any ideas on how to implement a fix to stop the overwriting of data when starting / deploying?

**Comment by younessidbakkasse** [comment]
I've added the ignore pattern, but you will need to use the Latest version of Shopify CLI, only to the push command, the pull one isn't, because I use it to save the settings made using the local development customizer. Thanks for your feedback 😀 
In a nutshell, when I run the serve with ```yarn start``` I use the local customizer to edit my theme settings localy but when i kill the serve all the settings are erased, so before killing the server I run ```yarn pull``` to save the settings localy.
